league_site/urls.py
from django.contrib import admin
from django.urls import include, path
""""""
urlpatterns = [
    path('', include('read_only_site.urls')),
    path('admin/', admin.site.urls),
]

read_only_site/urls.py
"""Manage the app urls"""

from django.urls import path
from . import views

app_name = 'read_only_site'
urlpatterns = [
    path('', views.index, name='index'),
    # Player stats (ex: /player/trucy)
    path('player/<str:player_name>/', views.player, name='player'),
    # Match view (ex: /match/1337)
    path('match/<int:match_pk>', views.match, name='match'),
    # Leaderboard
    path('leaderboard', views.leaderboard, name='leaderboard'),
    # Latest matches
    path('latest_matches', views.latest_matches, name='latest_matches')
]

read_only_site/models.py
"""Models for the read_only_site app"""

from django.db import models
from trueskill import Rating, backends, rate_1vs1, setup

# More details about the constants on https://trueskill.org
# the initial mean of ratings
TRUESKILL_MU = 300.0
# the initial standard deviation of ratings. The recommended value is a third of mu.
TRUESKILL_SIGMA = 100.0
# the distance which guarantees about 76% chance of winning.
# The recommended value is a half of sigma.
TRUESKILL_BETA = 50.0
# the dynamic factor which restrains a fixation of rating.
# The recommended value is sigma per cent.
TRUESKILL_TAU = 3.0

class Player(models.Model):
    """Manages a player during a league"""
    discord_id = models.IntegerField(default=0, blank=True, null=True)
    discord_handle = models.CharField(max_length=200, default=None)
    discord_nickname = models.CharField(max_length=200, default=None)
    jstris_handle = models.CharField(max_length=200, default=None)
    signup_date = models.DateTimeField(auto_now_add=True)
    trueskill_mu = models.FloatField(default=TRUESKILL_MU)
    trueskill_sigma = models.FloatField(default=TRUESKILL_SIGMA)
    banned = models.BooleanField(default=False)
    def __str__(self):
        """Returns a string in the format discord_nickname/jstris_handle to display"""
        return self.discord_nickname + '/' + self.jstris_handle

class Match(models.Model):
    """Manages a league match, in a tournament or not"""
    player_1 = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='+')
    player_2 = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='+')
    winner = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='+')
    match_identifier = models.CharField(max_length=200, blank=True, default='')
    played_on = models.DateTimeField(auto_now_add=True)
    player_1_trueskill_mu_before_match = models.FloatField(blank=True, default=0.0)
    player_1_trueskill_sigma_before_match = models.FloatField(blank=True, default=0.0)
    player_1_trueskill_mu_after_match = models.FloatField(blank=True, default=0.0)
    player_1_trueskill_sigma_after_match = models.FloatField(blank=True, default=0.0)
    player_2_trueskill_mu_before_match = models.FloatField(blank=True, default=0.0)
    player_2_trueskill_sigma_before_match = models.FloatField(blank=True, default=0.0)
    player_2_trueskill_mu_after_match = models.FloatField(blank=True, default=0.0)
    player_2_trueskill_sigma_after_match = models.FloatField(blank=True, default=0.0)
    tournament_match = models.BooleanField(default=False)
    def __str__(self):
        return (self.player_1.discord_nickname +
                ' VS ' +
                self.player_2.discord_nickname +
                ' on ' +
                str(self.played_on))
    def save(self):
        """Registers a match in the database"""
        if self.player_1.banned or self.player_2.banned:
            raise Exception('Can\'t play a match against a banned player!')
        if not self.pk:  # object is being created, thus no primary key field yet
            self.rate_match()
        return super(Match, self).save()
    def rate_match(self):
        """Use TrueSkill to modify players skill"""
        # TrueSkill setup
        setup(mu=TRUESKILL_MU, sigma=TRUESKILL_SIGMA, beta=TRUESKILL_BETA, tau=TRUESKILL_TAU)
        if 'scipy' in backends.available_backends():
            # scipy can be used in the current environment
            backends.choose_backend(backend='scipy')
        self.player_1_trueskill_mu_before_match = self.player_1.trueskill_mu
        self.player_1_trueskill_sigma_before_match = self.player_1.trueskill_sigma
        self.player_2_trueskill_mu_before_match = self.player_2.trueskill_mu
        self.player_2_trueskill_sigma_before_match = self.player_2.trueskill_sigma
        player_1_trueskill = Rating(self.player_1_trueskill_mu_before_match,
                                    self.player_1_trueskill_sigma_before_match)
        player_2_trueskill = Rating(self.player_2_trueskill_mu_before_match,
                                    self.player_2_trueskill_sigma_before_match)
        if self.winner == self.player_1:
            new_player_1_trueskill, new_player_2_trueskill = rate_1vs1(player_1_trueskill,
                                                                       player_2_trueskill)
        else:
            new_player_2_trueskill, new_player_1_trueskill = rate_1vs1(player_2_trueskill,
                                                                       player_1_trueskill)
        self.player_1_trueskill_mu_after_match = new_player_1_trueskill.mu
        self.player_1_trueskill_sigma_after_match = new_player_1_trueskill.sigma
        self.player_2_trueskill_mu_after_match = new_player_2_trueskill.mu
        self.player_2_trueskill_sigma_after_match = new_player_2_trueskill.sigma
        self.player_1.trueskill_mu = self.player_1_trueskill_mu_after_match
        self.player_1.trueskill_sigma = self.player_1_trueskill_sigma_after_match
        self.player_2.trueskill_mu = self.player_2_trueskill_mu_after_match
        self.player_2.trueskill_sigma = self.player_2_trueskill_sigma_after_match
        self.player_1.save()
        self.player_2.save()

read_only_site/views.py
"""Manage the read_only_site views"""

from django.db.models import Q
from django.shortcuts import get_object_or_404, render
from .models import Player, Match

# Create your views here.
def index(request):
    """Home page"""
    return render(request, 'read_only_site/index.html')

def player(request, player_name):
    """Stats for a single player"""
    player_to_get = get_object_or_404(Player, jstris_handle=player_name)
    # Get matches with that player
    matches = Match.objects.filter(Q(player_1=player_to_get) | Q(player_2=player_to_get)).order_by('-played_on')
    context = {'player': player_to_get, 'matches': matches}
    return render(request, 'read_only_site/player.html', context)

def match(request, match_pk):
    """Stats for a single match"""
    match_to_get = get_object_or_404(Match, pk=match_pk)
    context = {'match': match_to_get}
    return render(request, 'read_only_site/match.html', context)

def leaderboard(request):
    """Leaderboard, based on trueskill_mu"""
    players = Player.objects.filter(banned=False).exclude(trueskill_mu=300).order_by('-trueskill_mu')
    context = {'players': players}
    return render(request, 'read_only_site/leaderboard.html', context)

def latest_matches(request):
    """All matches, from latest to oldest"""
    matches = Match.objects.order_by('-played_on')
    context = {'matches': matches}
    return render(request, 'read_only_site/latest_matches.html', context)

read_only_site/templates/read_only_site/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <link rel="shortcut icon" type="image/png" href="{% static 'read_only_site/favicon.ico' %}">
    <title>Hard Drop League</title>

    <link rel="stylesheet" type="text/css" href="{% static 'read_only_site/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'read_only_site/css/custom.css' %}">
  </head>
  <body class="text-center">
  <nav class="site-header sticky-top py-1">
    <div class="container d-flex flex-column flex-md-row justify-content-between">
      <a class="py-2" href="{% url 'read_only_site:index' %}">
        <img src="{% static 'read_only_site/img/hard_drop_logo_slim.png' %}">
      </a>
      <a class="py-2 d-none d-md-inline-block" href="{% url 'read_only_site:leaderboard' %}">Leaderboard</a>
      <a class="py-2 d-none d-md-inline-block" href="{% url 'read_only_site:latest_matches' %}">Latest matches</a>
      <!--<a class="py-2 d-none d-md-inline-block" href="#">About</a>
      <a class="py-2 d-none d-md-inline-block" href="#">News</a>Soon™-->
    </div>
  </nav>

  <br><br>

  <main role="main" class="inner cover">
    {% block content %}
    {% endblock content %}
  </main>

  <footer class="footer">
    <div class="container">
      This site is in alpha stage. It'll get better with time.
    </div>
  </footer>
</body>
</html>

read_only_site/templates/read_only_site/index.html
{% extends "read_only_site/base.html" %}
{% load static %}
{% block content %}
<h2>Welcome to the Hard Drop League!</h2>

<img src="{% static 'read_only_site/img/hard_drop_logo.png' %}">

<h3>How do I register?</h3>
Go to the Hard Drop Discord
(<a href="https://discord.gg/harddrop">https://discord.gg/harddrop</a>),
and type <kbd>!register [jstris handle]</kbd> in the #compete channel.

<br><br>

<h3>How do I submit my score?</h3>
The loser of the match has to type
<kbd>!winner @mention</kbd>,
with @mention mentionning the winner.

<br><br>

<h3>What kind of matches can I play?</h3>
It's up to you! As long as you play jstris
(<a href="https://jstris.jezevec10.com/">https://jstris.jezevec10.com/</a>)
 and agree with the other player what kind of format you want to play, it's fine!
The base format should be first to 7.

<br><br>

<h3>What is the ranking?</h3>
The ranking is a number determining your rank.
The higher the better! You win ranking points by winning matches, and lose ranking
points by losing matches.

A highly ranked player will lose a lot of points if they lose against a lower ranked
player; but a low ranked player will win a lot of points if they win against a
highly ranked player!

The more matches you do, the more your ranking will match your actual rank.

<br><br>

<h3>I need help! Something's wrong!</h3>
Mention <kbd style="color:pink">@Lady Trucy</kbd> on the Hard Drop Discord.
{% endblock %}

read_only_site/templates/read_only_site/latest_matches.html
{% extends "read_only_site/base.html" %}
{% block content %}
<h2>Latest Matches</h2>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Player 1 (Discord/jstris)</th>
            <th>Player 2 (Discord/jstris)</th>
            <th>Date</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
{% for match in matches %}
        <tr>
            <td><a href="{% url 'read_only_site:player' match.player_1.jstris_handle %}">{{match.player_1}}</a></td>
            <td><a href="{% url 'read_only_site:player' match.player_2.jstris_handle %}">{{match.player_2}}</a></td>
            <td>{{match.played_on}}</td>
            <td><a href="{% url 'read_only_site:match' match.pk %}">Match details</a></td>
        </tr>
{% endfor %}
    </tbody>
</table>
{% endblock content %}

read_only_site/templates/read_only_site/leaderboard.html
{% extends "read_only_site/base.html" %}
{% block content %}
<h2>Leaderboard</h2>
(Displays only players who played at least 1 match)

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Rank</th>
            <th>Discord Name</th>
            <th>jstris Name</th>
            <th>Ranking</th>
        </tr>
    </thead>
    <tbody>
{% for player in players %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td><a href="{% url 'read_only_site:player' player.jstris_handle %}">
            {{ player.discord_nickname }}</a></td>
            <td><a href="https://jstris.jezevec10.com/u/{{ player.jstris_handle }}">
            {{ player.jstris_handle }}</a></td>
            <td>{{player.trueskill_mu | floatformat:"0"}}</td>
        </tr>
{% endfor %}
    </tbody>
</table>
{% endblock content %}

read_only_site/templates/read_only_site/match.html
{% extends "read_only_site/base.html" %}
{% block content %}
<h2>{{match.player_1.discord_nickname}} VS {{match.player_2.discord_nickname}}</h2>

<br><br>

<h3>Winner: {{match.winner}}</h3>

<br><br>

<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">
          <a href="{% url 'read_only_site:player' match.player_1.jstris_handle %}">{{match.player_1}}</a>
        </h4>
          <div class="container-fluid">
            <div class="row">
              <div class="col large-text">Old rank:</div>
              <div class="col large-text">
                {{match.player_1_trueskill_mu_before_match| floatformat:"0"}}
              </div>
            </div>
            <div class="row">
              <div class="col large-text">New rank:</div>
              <div class="col large-text">
                {{match.player_1_trueskill_mu_after_match| floatformat:"0"}}
              </div>
            </div>
          </div>
      </div>
    </div>
    <div class="col">
      <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">
          <a href="{% url 'read_only_site:player' match.player_2.jstris_handle %}">{{match.player_2}}</a>
        </h4>
          <div class="container-fluid">
            <div class="row">
              <div class="col large-text">Old rank:</div>
              <div class="col large-text">
                {{match.player_2_trueskill_mu_before_match| floatformat:"0"}}
              </div>
            </div>
            <div class="row">
              <div class="col large-text">New rank:</div>
              <div class="col large-text">
                {{match.player_2_trueskill_mu_after_match| floatformat:"0"}}
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

read_only_site/templates/read_only_site/player.html
{% extends "read_only_site/base.html" %}
{% block content %}
<h2>{{player}}</h2>

<br><br>

<h3>Ranking: {{player.trueskill_mu | floatformat:"0"}}</h3>

<h4>jstris profile:
<a href="https://jstris.jezevec10.com/u/{{ player.jstris_handle }}">
{{ player.jstris_handle }}</a></h4>

<br><br>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Player 1 (Discord/jstris)</th>
            <th>Player 2 (Discord/jstris)</th>
            <th>Date</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
{% for match in matches %}
        <tr>
            <td><a href="{% url 'read_only_site:player' match.player_1.jstris_handle %}">{{match.player_1}}</a></td>
            <td><a href="{% url 'read_only_site:player' match.player_2.jstris_handle %}">{{match.player_2}}</a></td>
            <td>{{match.played_on}}</td>
            <td><a href="{% url 'read_only_site:match' match.pk %}">Match details</a></td>
        </tr>
{% endfor %}
    </tbody>
</table>

{% endblock content %}